spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/parkinglot
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: qwedfg123

    jwt:
      secret: c3ByaW5nLWJvb3QtcGFya2luZ0xvdC1wcm9qZWN0LWp3dC1zZWNyZXQta2V5Cg==

geocoding:
  key: AIzaSyB5J_0k9aKuHEIjTJR7fYwoPx0kSU09lNQ