spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/parkinglot
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: qwedfg123

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true