spring:
  profiles:
    include: secret

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: 127.0.0.1
    port: 6379

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher